BestQA.Web/Controllers/QuestionController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using BestQA.Commands;
using BestQA.QueryService;
using BestQA.QueryService.DTOs;
using BestQA.QueryService.Grid;
using BestQA.Web.Extensions;
using BestQA.Web.Models;
using ECommon.Utilities;
using ENode.Commanding;
using Microsoft.AspNet.Identity;

namespace BestQA.Web.Controllers
{
    public class QuestionController : Controller
    {
        private readonly ICommandService _commandService;
        private readonly IQuestionQuery _queryService;
        public QuestionController(ICommandService commandService, IQuestionQuery questionQuery)
        {
            _commandService = commandService;
            _queryService = questionQuery;
        }
        //
        // GET: /Question/
        public ActionResult Index(string tab)
        {
            ViewBag.Questions = "active";
            if (string.IsNullOrEmpty(tab))
                tab = "recent";
            ViewBag.ActiveTab = tab;
            return View();
        }
        //
        // GET: /Question/Details/5
        public ActionResult Details(string id)
        {
            ViewBag.PageMode = "update";   //页面模式
            return View(_queryService.Find(id));
        }

        /// <summary>
        /// 创建问题页面
        /// </summary>
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Create = "active";
            ViewBag.PageMode = "create"; 
            QuestionDTO postViewModel = new QuestionDTO { Id = string.Empty };
            return View("Details", postViewModel);
        }

        /// <summary>
        /// 返回全部问题列表
        /// </summary>
        [HttpPost]
        public JsonResult Get(PostFilterViewModel filterView)
        {
            IList<QuestionDTO> questions = _queryService.FindAll().ToList();
            return Json(new { data = questions }, JsonRequestBehavior.AllowGet);
        }
        //
        // POST: /Question/Create
        [HttpPost]
        [Authorize]
        [AsyncTimeout(5000)]
        public async Task<JsonResult> Create(QuestionModel question)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelErrorModel> modelErrors = ModelStateHelpers.GetModelStateErrors(ModelState);
                return Json(new { validationErrors = modelErrors }, JsonRequestBehavior.AllowGet);
            }
            var newId = ObjectId.GenerateNewStringId();
            var result = await _commandService.ExecuteAsync(
            new CreateQuestionCmd(question.Title,
                question.Content,
                question.Reward,
                question.Tag,
                User.Identity.GetUserName()) 
                { AggregateRootId = newId });
            if (result.Data.Status == CommandStatus.Success)
            {
                return Json(new { data = newId }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { data = "error" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        [AsyncTimeout(5000)]
        public async Task<JsonResult> VoteUp(QuestionDTO question)
        {
            return await ExecuteAsync(new QuestionVoteUpCmd(question.Id, User.Identity.GetUserName()));
        }

        [HttpPost]
        [Authorize]
        [AsyncTimeout(5000)]
        public async Task<JsonResult> VoteDown(QuestionDTO question)
        {
            return await ExecuteAsync(new QuestionVoteDownCmd(question.Id, User.Identity.GetUserName()));
        }

        private async Task<JsonResult> ExecuteAsync(Command<string> command)
        {
            var result = await _commandService.ExecuteAsync(command);
            if (result.Data.Status == CommandStatus.Success)
            {
                return Json(new { data = "success" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { data = result.Data.ErrorMessage }, JsonRequestBehavior.AllowGet);
        }
       
    }
}

BestQA.Web/Views/Shared/Sidebar.cshtml
<div class="col-md-3">
    <div class="well">
        <h4>热门标签</h4>
        <br />C# asp.net mvc nodejs angularjs<br />
    </div>
</div>

BestQA.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 基于DDD思想与ENode框架的问答系统</title>

    @Scripts.Render("~/bundles/baseJavascriptBundle")
    @Scripts.Render("~/bundles/angularPlugins")
    @Scripts.Render("~/bundles/jqueryPlugins")

    @Styles.Render("~/Content/bestQACss")
    <script>
        angular.module('bestQA', ['blockUI', 'ngTable', 'ui.pagedown']);
    </script>
</head>
<body ng-app="bestQA">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BestQ&A", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home", null, new { @class = ViewBag.Home })</li>
                    <li>@Html.ActionLink("问题列表", "Index", "Question", null, new {@class = ViewBag.Questions})</li>
                    <li>@Html.ActionLink("我要提问", "Create", "Question", null, new { @class = ViewBag.Create })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Best Question & Answer @@ yubaolee</p>
        </footer>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>